version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    networks:
      - api-mysql-network
    container_name: luggage-api-api
    restart: always
    ports:
      - "8080:8080"

  # db:
  #   image: mysql:5.7
  #   networks:
  #     - api-mysql-network
  #   container_name: luggage-api-mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - 3306:3306

  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    networks:
      - api-mysql-network
    container_name: luggage-api-mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_AGENT_ENABLED=true
    ports:
      - 1433:1433

networks:
  api-mysql-network:
    driver: bridge
